facts = [
'Grapes light on fire in microwave', 
' There are almost 8 million possible seven digit phone numbers per area code', 
" McDonald's once created a bubble gum flavored broccoli", 
' The average mammabl takes 21 seconds to empty its bladder',
' Chewing gum is banned in singapore', 
' The average U.S. household has 300,000 things in it',
' The 1939 novel "Gadsby" is the longest book ever published that doesn\'t contain letter "e"',
' Lobsters have clear blood', ' The first item sold on eBay was a broken laser pointer',
'Japan is suffering from ninja shortage', 'The longest place name in the world is 85 letters long',
"Threr was a prehistoric dragonfly that's wings spanned more than two feet",
'Bubble wrap was originally invented as wallpaper',
'Shakespeare invented more that 1,700 words', 
"Santa claus was given an official pilot's licence in 1927",
"Einstein's brain was stolen when he died",
'Scientists made a "nanoguitar" the size of a human blood cell', 
' The top speed ot the winnig car in the first U.S. race was seven mile per hour',
"Antactica is covered in a sheet of ice that's 7,000 feet thick", 
'There is a Guiness World Record for the stretchiest skin',
'One of the largest pyramids in the world is a Bass Pro Shops in Memphis in Tennessee',
' Scientists once gave mice superhero-like night vision using nanoparticles',
'Extreme ironing is an actual sport',
'A lifeboat drill was canceled in the morning of Titanic tragedy',
"It's illegal to own just on guinea pig in switzerland", 
"There's a planet that's shaped like potato", 
'It only take size minute for alcohol to affect your brain', 
'"Strengths" is the longest word in the English language with one vowel',
'Shark attacks threaten the internet', 
'"Q" is the only letter that doesn"t appear in any U.S. state names', 
'You can get your eyeball tattooed', "There's a toilete museum",
 "It's against the law to feed pigeons on the streets or sidewalks of San Francisco.\n"
 ]